// Package jobs is the v0.3-1 follow-up that brings POSIX job control to
// aish: a Job + JobTable abstraction, plus the SIGCHLD / TTY-ownership
// helpers that `fg` / `bg` / `jobs` and the background-dispatch path
// in shell/runExternal sit on.
//
// Closes #83 (jobs/fg/bg built-ins) and #84 (process-group management).
// v0.2-2 (PR #179) already wires PTY allocation with foreground-pgrp
// routing; this package adds the bookkeeping and built-ins. Windows
// is stubbed — JobObject-based job control is v1.0 work.
//
// Concurrency contract:
//
//   - JobTable methods are safe to call from the REPL goroutine, from
//     the SIGCHLD reaper goroutine, and from any built-in. Each method
//     acquires the table mutex for the duration of the operation.
//   - The reaper goroutine drains Wait4 results into the table; it
//     NEVER reaps a pid the REPL has marked as foreground (DoubleReap
//     test in jobs_test.go covers this).
//   - The table emits "Done notices" through a buffered channel; the
//     REPL drains them on each prompt render.
package jobs

import (
	"fmt"
	"strings"
	"sync"
)

// JobStatus is the externally-observable status of a Job. Maps to the
// `Running` / `Stopped` / `Done` lines bash prints in `jobs`.
type JobStatus int

const (
	// StatusRunning means the job is executing in the background, OR is
	// the foreground job (the REPL goroutine is blocked on Wait).
	StatusRunning JobStatus = iota
	// StatusStopped means the job received SIGSTOP/SIGTSTP and is
	// suspended. `bg` resumes it in the background; `fg` resumes it in
	// the foreground.
	StatusStopped
	// StatusDone means the job's leader exited (or was killed by a
	// signal). Done jobs are reported on the next prompt and then
	// evicted from the table.
	StatusDone
)

// String renders the bash-style status word used by `jobs`.
func (s JobStatus) String() string {
	switch s {
	case StatusRunning:
		return "Running"
	case StatusStopped:
		return "Stopped"
	case StatusDone:
		return "Done"
	default:
		return "Unknown"
	}
}

// Job is the bookkeeping record for one background or stopped job.
//
// The Pgid is the kernel process-group ID — the same value the shell
// passes to `kill(-pgid, sig)` to signal the entire group, and to
// `TIOCSPGRP` to hand the TTY over.
//
// Cmdline is the human-readable original line (`sleep 30`, `yes | head -n5`)
// so `jobs` can render something meaningful.
//
// ExitCode is meaningful only when Status == StatusDone.
type Job struct {
	// ID is the shell-local job number (`%1`, `%2`, …). Stable across
	// the job's lifetime; reused only after Reap evicts it.
	ID int
	// Pgid is the process-group ID. Equal to the leader pid for a
	// single-stage pipeline; equal to the first stage's pid otherwise.
	Pgid int
	// LeaderPid is the pid of the first stage (the pgrp leader).
	LeaderPid int
	// Cmdline is the user-typed command line, used for `jobs`
	// formatting and Done notifications.
	Cmdline string
	// Status is the current job state. See JobStatus.
	Status JobStatus
	// ExitCode is set when Status == StatusDone. POSIX-style: signal
	// kills encode as 128+signum.
	ExitCode int
	// Foreground is true when the REPL goroutine has taken the TTY
	// for this job and is blocking on Wait. The reaper goroutine
	// MUST NOT call wait* on foreground jobs — the REPL owns them.
	Foreground bool
}

// JobTable holds the live set of background + stopped jobs. Methods
// are safe for concurrent use; the table guards all state with mu.
//
// Lifecycle: created once per Shell at construction time, torn down
// in Shell.Close() by Reap()'ing every remaining job.
type JobTable struct {
	mu      sync.Mutex
	jobs    map[int]*Job // keyed by ID
	nextID  int          // monotonic; rolls only when no live jobs
	current int          // job ID flagged `+` (most recent)
	prev    int          // job ID flagged `-` (second-most-recent)
	notices chan Notice  // buffered; REPL drains on each prompt
}

// Notice is a "job finished / changed" message the REPL prints on the
// next prompt. Generated by Update when a job transitions to Done or
// Stopped while in the background.
type Notice struct {
	// ID is the bash-style job number.
	ID int
	// Flag is "+" / "-" / " " — same scheme as `jobs`.
	Flag string
	// Status is the new status as of this notice.
	Status JobStatus
	// Cmdline is the user-typed line.
	Cmdline string
	// ExitCode is meaningful only when Status == StatusDone.
	ExitCode int
}

// NewJobTable returns an empty table. The notices channel buffer is
// large enough that the SIGCHLD reaper can post several status
// changes between prompts without blocking; in practice users rarely
// see more than one or two pending at a time.
func NewJobTable() *JobTable {
	return &JobTable{
		jobs:    make(map[int]*Job),
		nextID:  1,
		notices: make(chan Notice, 32),
	}
}

// Add registers a freshly-spawned background job. Returns a copy of
// the newly-stored Job (callers MUST NOT cache mutable pointers into
// the table — use the lookup methods to read live state and the
// SetStatus / MarkForeground methods to mutate).
//
// The new job becomes `current` (+) and the previous current
// becomes `prev` (-).
func (jt *JobTable) Add(pgid, leaderPid int, cmdline string, status JobStatus) Job {
	jt.mu.Lock()
	defer jt.mu.Unlock()
	id := jt.nextID
	jt.nextID++
	j := &Job{
		ID:        id,
		Pgid:      pgid,
		LeaderPid: leaderPid,
		Cmdline:   cmdline,
		Status:    status,
	}
	jt.jobs[id] = j
	jt.prev = jt.current
	jt.current = id
	return *j
}

// AddForeground registers a job that the REPL has spawned in the
// foreground (e.g. a Ctrl-Z-eligible command). Used so a subsequent
// SIGTSTP transition can be recorded against an existing entry
// rather than creating a fresh one.
//
// The job is marked Foreground=true so the reaper goroutine skips
// it; the REPL goroutine owns the Wait.
func (jt *JobTable) AddForeground(pgid, leaderPid int, cmdline string) Job {
	j := jt.Add(pgid, leaderPid, cmdline, StatusRunning)
	jt.MarkForeground(j.ID)
	j.Foreground = true
	return j
}

// Find returns the job matching spec. spec accepts:
//
//   - "%n"   → job ID n
//   - "%+"   → the current (+) job
//   - "%-"   → the previous (-) job
//   - ""     → the current (+) job (bash `fg` / `bg` default)
//   - "n"    → job ID n (without leading %, for ergonomic callers)
//
// Returns a COPY of the matched job (so callers can't accidentally
// race on the internal *Job by mutating it without the table lock)
// and ok=true. (zero-value Job, false) on no match.
func (jt *JobTable) Find(spec string) (Job, bool) {
	jt.mu.Lock()
	defer jt.mu.Unlock()
	spec = strings.TrimSpace(spec)
	if spec == "" || spec == "%+" || spec == "%" {
		if jt.current == 0 {
			return Job{}, false
		}
		j, ok := jt.jobs[jt.current]
		if !ok {
			return Job{}, false
		}
		return *j, true
	}
	if spec == "%-" {
		if jt.prev == 0 {
			return Job{}, false
		}
		j, ok := jt.jobs[jt.prev]
		if !ok {
			return Job{}, false
		}
		return *j, true
	}
	idStr := strings.TrimPrefix(spec, "%")
	var id int
	if _, err := fmt.Sscanf(idStr, "%d", &id); err != nil {
		return Job{}, false
	}
	j, ok := jt.jobs[id]
	if !ok {
		return Job{}, false
	}
	return *j, true
}

// FindByPid returns the job whose LeaderPid matches pid. The reaper
// goroutine uses this to attribute a Wait4 result to a known job;
// returns (zero-value Job, false) when pid belongs to a process aish
// is not tracking (defensive — should not happen in normal operation).
func (jt *JobTable) FindByPid(pid int) (Job, bool) {
	jt.mu.Lock()
	defer jt.mu.Unlock()
	for _, j := range jt.jobs {
		if j.LeaderPid == pid {
			return *j, true
		}
	}
	return Job{}, false
}

// IsForeground reports whether the table has marked the given pid as
// the foreground job. The reaper goroutine MUST consult this before
// calling wait* on a pid; otherwise the REPL's synchronous Wait would
// race against the reaper and either side could see ECHILD.
func (jt *JobTable) IsForeground(pid int) bool {
	jt.mu.Lock()
	defer jt.mu.Unlock()
	for _, j := range jt.jobs {
		if j.LeaderPid == pid && j.Foreground {
			return true
		}
	}
	return false
}

// SetStatus updates a job's status. When the job is in the background
// and transitions to Done or Stopped, a Notice is enqueued for the
// REPL to render on its next prompt. Foreground jobs do NOT emit
// notices — the REPL sees the status change directly via Wait return.
func (jt *JobTable) SetStatus(id int, status JobStatus, exit int) {
	jt.mu.Lock()
	j, ok := jt.jobs[id]
	if !ok {
		jt.mu.Unlock()
		return
	}
	prev := j.Status
	j.Status = status
	j.ExitCode = exit
	notify := !j.Foreground && (status == StatusDone || status == StatusStopped) && prev != status
	flag := jt.flagForLocked(id)
	cmdline := j.Cmdline
	jt.mu.Unlock()
	if notify {
		// Non-blocking send: if the buffer is full the notice is
		// dropped rather than wedging the reaper.
		select {
		case jt.notices <- Notice{ID: id, Flag: flag, Status: status, Cmdline: cmdline, ExitCode: exit}:
		default:
		}
	}
}

// ClearForeground drops the Foreground flag on the job with the given
// pid. Called when `fg` returns control to the REPL (job exited or
// was stopped) so subsequent SIGCHLD events can be reaped normally.
func (jt *JobTable) ClearForeground(pid int) {
	jt.mu.Lock()
	defer jt.mu.Unlock()
	for _, j := range jt.jobs {
		if j.LeaderPid == pid {
			j.Foreground = false
			return
		}
	}
}

// MarkForeground sets the Foreground flag on the job with the given
// ID. Used by `fg` to claim ownership of an existing background or
// stopped job. No-op if id doesn't exist.
func (jt *JobTable) MarkForeground(id int) {
	jt.mu.Lock()
	defer jt.mu.Unlock()
	if j, ok := jt.jobs[id]; ok {
		j.Foreground = true
	}
}

// SetRunning unconditionally flips a job's status to Running and
// clears the exit code. Used by `bg` after SIGCONT. Idempotent.
func (jt *JobTable) SetRunning(id int) {
	jt.mu.Lock()
	defer jt.mu.Unlock()
	if j, ok := jt.jobs[id]; ok {
		j.Status = StatusRunning
		j.ExitCode = 0
	}
}

// Reap removes Done jobs from the table. Returns the IDs that were
// evicted, in ascending order, so callers can confirm tear-down.
func (jt *JobTable) Reap() []int {
	jt.mu.Lock()
	defer jt.mu.Unlock()
	var removed []int
	for id, j := range jt.jobs {
		if j.Status == StatusDone {
			delete(jt.jobs, id)
			removed = append(removed, id)
		}
	}
	if len(jt.jobs) == 0 {
		// Bash resets job IDs to 1 when the table empties.
		jt.nextID = 1
		jt.current = 0
		jt.prev = 0
	} else {
		// Repair current/prev if either pointed at a removed job.
		if _, ok := jt.jobs[jt.current]; !ok {
			jt.current = jt.highestIDLocked()
		}
		if _, ok := jt.jobs[jt.prev]; !ok {
			jt.prev = jt.secondHighestIDLocked()
		}
	}
	return removed
}

// List returns a snapshot of the current job table, sorted by ID
// ascending. Each row is `[<id>]<flag>  <status>  <cmdline>` —
// matches bash's `jobs` output format.
func (jt *JobTable) List() []string {
	jt.mu.Lock()
	defer jt.mu.Unlock()
	if len(jt.jobs) == 0 {
		return nil
	}
	ids := make([]int, 0, len(jt.jobs))
	for id := range jt.jobs {
		ids = append(ids, id)
	}
	// simple ascending sort (small N — rarely > 10)
	for i := 1; i < len(ids); i++ {
		for k := i; k > 0 && ids[k-1] > ids[k]; k-- {
			ids[k-1], ids[k] = ids[k], ids[k-1]
		}
	}
	out := make([]string, 0, len(ids))
	for _, id := range ids {
		j := jt.jobs[id]
		flag := jt.flagForLocked(id)
		out = append(out, fmt.Sprintf("[%d]%s  %-8s %s", id, flag, j.Status.String(), j.Cmdline))
	}
	return out
}

// PendingNotices drains the notice queue without blocking. Called by
// the REPL on every prompt render so backgrounded job completions
// surface in time. Each returned Notice is for the caller to format
// and print to stderr.
func (jt *JobTable) PendingNotices() []Notice {
	var out []Notice
	for {
		select {
		case n := <-jt.notices:
			out = append(out, n)
		default:
			return out
		}
	}
}

// Snapshot returns a copy of every live job. Used by Shell.Close()
// to find still-running children that need killing on shutdown.
func (jt *JobTable) Snapshot() []Job {
	jt.mu.Lock()
	defer jt.mu.Unlock()
	out := make([]Job, 0, len(jt.jobs))
	for _, j := range jt.jobs {
		out = append(out, *j)
	}
	return out
}

// Current returns the current (`+`) job ID; 0 when the table is empty.
func (jt *JobTable) Current() int {
	jt.mu.Lock()
	defer jt.mu.Unlock()
	return jt.current
}

// SetCurrent promotes id to current (`+`); the previous current
// becomes prev (`-`). Used by `fg` / `bg` which redefine the
// "most-recent" job per bash semantics.
func (jt *JobTable) SetCurrent(id int) {
	jt.mu.Lock()
	defer jt.mu.Unlock()
	if _, ok := jt.jobs[id]; !ok {
		return
	}
	if jt.current == id {
		return
	}
	jt.prev = jt.current
	jt.current = id
}

// flagForLocked returns "+" / "-" / " " for the given job ID.
// Caller must hold jt.mu.
func (jt *JobTable) flagForLocked(id int) string {
	switch id {
	case jt.current:
		return "+"
	case jt.prev:
		return "-"
	default:
		return " "
	}
}

// highestIDLocked returns the largest ID in the table; 0 if empty.
// Caller must hold jt.mu.
func (jt *JobTable) highestIDLocked() int {
	best := 0
	for id := range jt.jobs {
		if id > best {
			best = id
		}
	}
	return best
}

// secondHighestIDLocked returns the second-largest ID in the table;
// 0 if there are fewer than two. Caller must hold jt.mu.
func (jt *JobTable) secondHighestIDLocked() int {
	first, second := 0, 0
	for id := range jt.jobs {
		switch {
		case id > first:
			second = first
			first = id
		case id > second:
			second = id
		}
	}
	return second
}
